### PR TITLE
Port the library to TS

### PR DESCRIPTION
**Pull request by AIRTucha**
Port library source code to TS enables the generation of correct typings. Please, squash it, since commit msgs are not perfect.

### CODE REVIEW

**Comment by RyanZim** [comment]
As a maintainer, I don't know Typescript, so this would make me unable to maintain the library.

**Comment by AIRTucha** [comment]
Don't worry; it was just a friendly attempt to help the community since it is much easier to have consistent typing in that way, but I would not mind if you will not approve it. Nevertheless, if you know JS and any statically typed language, you practically know TypeScript;)

As developers we should not be afraid of new tech, I suppose.

**Comment by RyanZim** [comment]
Yeah, unfortunately, JS is the only language I really know. :frowning:

**Comment by AIRTucha** [comment]
Btw, the codebase is not big. I would be able to assist you in maintenance if you let.

**Pull request closed without merging**
