### PR TITLE
Add Atomic Write Methods

### PR DESCRIPTION
**Pull request by jaruba**
Implemented atomic save methods, as per the discussion from: https://github.com/nathanbuchar/electron-settings/issues/110

### CODE REVIEW

**Comment by RyanZim** [comment]
This seems like a specialized use-case, not broad enough to warrant adding a dependency to jsonfile for. Also, this could be a breaking change since it'd be creating temp files. @jprichardson?

**Comment by jprichardson** [comment]
@RyanZim agreed.

This could be a separate package: `atomic-jsonfile` or something like that.

**Comment by wilburforce83** [comment]
what happened to this? I am having problems with power outages causing users to lose saved data. Is there a way to implement this? thanks

**Comment by jaruba** [comment]
@wilburforce83 your welcome to use my fork which has atomic save implemented, if you want:

https://github.com/jaruba/node-jsonfile

**Pull request closed without merging**
